export const SESSION_RECOVER = 'SESSION_RECOVER';
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_DELETE = 'SESSION_DELETE';

export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';
export const APP_TOKEN_UPDATE = 'APP_TOKEN_UPDATE';

export const FILES_SET_FILES_LIST = 'FILES_SET_FILES_LIST';
export const FILES_SET_FOLDER_LIST = 'FILES_SET_FOLDER_LIST';
